import type { AgentSpec } from './agentSpec'
import { artifactFromTemplate } from './artifactTemplates'

export const AI_TEAM_AGENT_CATALOG: AgentSpec[] = [
  {
    id: 'agent-research',
    role: 'Research Agent',
    modelId: 'claude-sonnet-4.6',
    inputs: [
      artifactFromTemplate('market_scan_notes'),
      artifactFromTemplate('competitor_links_bundle'),
      artifactFromTemplate('customer_interview_transcript_long'),
    ],
    outputs: [
      artifactFromTemplate('prd_medium', { id: 'research-customer-segments', name: 'Customer segment definition' }),
      artifactFromTemplate('market_scan_notes', { id: 'research-risk-list', name: 'Problem and risk list' }),
    ],
    callsPerRun: 2,
    retryRate: 0.1,
    cacheHitRate: 0,
    batchEnabled: false,
    humanReviewGate: 'sample',
    assignedTasks: ['market research', 'customer interview analysis'],
    frequency: { unit: 'week', count: 5 },
  },
  {
    id: 'agent-pm',
    role: 'PM Agent',
    modelId: 'claude-sonnet-4.6',
    inputs: [artifactFromTemplate('prd_medium'), artifactFromTemplate('market_scan_notes')],
    outputs: [artifactFromTemplate('prd_medium', { id: 'pm-mvp-scope', name: 'MVP scope' }), artifactFromTemplate('user_flow')],
    callsPerRun: 2,
    retryRate: 0.08,
    cacheHitRate: 0.1,
    batchEnabled: false,
    humanReviewGate: 'sample',
    assignedTasks: ['problem framing', 'PRD writing'],
    frequency: { unit: 'month', count: 4 },
  },
  {
    id: 'agent-design',
    role: 'Design Agent',
    modelId: 'gemini-3.1-flash',
    inputs: [artifactFromTemplate('prd_medium'), artifactFromTemplate('user_flow')],
    outputs: [artifactFromTemplate('screen_spec_set'), artifactFromTemplate('component_list')],
    callsPerRun: 2,
    retryRate: 0.05,
    cacheHitRate: 0,
    batchEnabled: false,
    humanReviewGate: 'sample',
    assignedTasks: ['screen planning', 'component planning'],
    frequency: { unit: 'month', count: 6 },
  },
  {
    id: 'agent-engineering',
    role: 'Engineering Agent',
    modelId: 'claude-sonnet-4.6',
    inputs: [artifactFromTemplate('prd_medium'), artifactFromTemplate('screen_spec_set'), artifactFromTemplate('codebase_context_long'), artifactFromTemplate('error_log_bundle')],
    outputs: [artifactFromTemplate('implementation_plan'), artifactFromTemplate('test_result_summary')],
    callsPerRun: 5,
    retryRate: 0.15,
    cacheHitRate: 0.2,
    batchEnabled: false,
    humanReviewGate: 'sample',
    assignedTasks: ['code implementation', 'test repair'],
    frequency: { unit: 'week', count: 5 },
  },
  {
    id: 'agent-marketing',
    role: 'Marketing Agent',
    modelId: 'gemini-3.1-flash',
    inputs: [artifactFromTemplate('prd_medium'), artifactFromTemplate('market_scan_notes')],
    outputs: [artifactFromTemplate('landing_copy'), artifactFromTemplate('seo_keyword_brief')],
    callsPerRun: 1,
    retryRate: 0.05,
    cacheHitRate: 0,
    batchEnabled: true,
    humanReviewGate: 'sample',
    assignedTasks: ['landing page copy', 'content draft'],
    frequency: { unit: 'week', count: 3 },
  },
  {
    id: 'agent-sales',
    role: 'Sales Agent',
    modelId: 'gemini-3.1-flash',
    inputs: [artifactFromTemplate('lead_profile'), artifactFromTemplate('prd_medium')],
    outputs: [artifactFromTemplate('cold_email_sequence')],
    callsPerRun: 1,
    retryRate: 0.05,
    cacheHitRate: 0,
    batchEnabled: true,
    humanReviewGate: 'sample',
    assignedTasks: ['cold email', 'objection handling'],
    frequency: { unit: 'customer', count: 1, denominatorCount: 120 },
  },
  {
    id: 'agent-cs',
    role: 'CS Agent',
    modelId: 'claude-haiku-4.5',
    inputs: [artifactFromTemplate('support_ticket'), artifactFromTemplate('knowledge_base_context')],
    outputs: [artifactFromTemplate('support_reply_draft')],
    callsPerRun: 1,
    retryRate: 0.08,
    cacheHitRate: 0.5,
    batchEnabled: false,
    humanReviewGate: 'sample',
    assignedTasks: ['customer support reply', 'FAQ update'],
    frequency: { unit: 'customer', count: 1, denominatorCount: 300 },
  },
  {
    id: 'agent-ops',
    role: 'Ops Agent',
    modelId: 'gemini-3.1-flash',
    inputs: [artifactFromTemplate('meeting_transcript'), artifactFromTemplate('knowledge_base_context')],
    outputs: [artifactFromTemplate('action_item_summary')],
    callsPerRun: 1,
    retryRate: 0.05,
    cacheHitRate: 0.4,
    batchEnabled: true,
    humanReviewGate: 'none',
    assignedTasks: ['meeting summary', 'document search'],
    frequency: { unit: 'week', count: 3 },
  },
  {
    id: 'agent-finance-legal',
    role: 'Finance/Legal Review Agent',
    modelId: 'claude-sonnet-4.6',
    inputs: [artifactFromTemplate('contract_excerpt'), artifactFromTemplate('finance_cost_data')],
    outputs: [artifactFromTemplate('action_item_summary', { id: 'legal-risk-flags', name: 'Risk flags' })],
    callsPerRun: 2,
    retryRate: 0.05,
    cacheHitRate: 0,
    batchEnabled: false,
    humanReviewGate: 'all',
    assignedTasks: ['contract review', 'cost policy review'],
    frequency: { unit: 'month', count: 2 },
  },
]
